TK4_E11/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('',include('gilangcy.urls')),
    path('',include('kevin.urls')),
    path('', include('alishayb.urls', namespace="alishayb")),
    path('', include('dodo.urls', namespace="dodo"))
]

dodo/urls.py
from django.urls import path
from . import views

app_name = "dodo"

urlpatterns = [
    path('get-lokasi-alamat/<slug:id_lokasi>', views.locationIDToAddressEndpoint, name="locationIDToAddressEndpoint"),
    path('get-faskes-tipe/<slug:id_tipe>', views.faskesCodeToTypeNameEndpoint, name="faskesCodeToTypeNameEndpoint"),
    path('list-faskes/', views.readFaskes, name="readFaskes"),
    path('delete-faskes/<slug:kode_faskes>', views.deleteFaskes, name="deleteFaskes"),
    path('update-faskes/<slug:kode_faskes>', views.updateFaskes, name="updateFaskes"),
    path('create-faskes/', views.createFaskes, name="createFaskes")
]

kevin/urls.py
from django.urls import path
from . import views

app_name = 'kevin'

urlpatterns = [
    path('createKendaraan/', views.createKendaraan, name='createKendaraan'),
    path('readKendaraan/', views.readKendaraan, name='readKendaraan'),
    path('deleteKendaraan/<slug:delete_id>/',views.deleteKendaraan, name='deleteKendaraan'),
    path('updateKendaraan/<slug:update_id>/',views.updateKendaraan, name='updateKendaraan'),

    path('createLokasi/', views.createLokasi, name='createLokasi'),
    path('readLokasi/', views.readLokasi, name='readLokasi'),
    path('deleteLokasi/<slug:delete_id>/',views.deleteLokasi, name='deleteLokasi'),
    path('updateLokasi/<slug:update_id>/',views.updateLokasi, name='updateLokasi'),

    path('createBatchPengiriman/', views.createBatchPengiriman, name='createBatchPengiriman'),
]

kevin/models.py
from django.db import models

# Create your models here.

kevin/forms.py
from django import forms

PROVINSI= [
    ('Aceh', 'Aceh'),
    ('Sumatra Utara', 'Sumatra Utara'),
    ('Sumatra Barat', 'Sumatra Barat'),
    ('Riau', 'Riau'),
    ('Kepulauan Riau', 'Kepulauan Riau'),
    ('Jambi', 'Jambi'),
    ('Bengkulu', 'Bengkulu'),
    ('Sumatra Selatan', 'Sumatra Selatan'),
    ('Kepulauan Bangka Belitung', 'Kepulauan Bangka Belitung'),
    ('Lampung', 'Lampung'),
    ('Banten', 'Banten'),
    ('Jawa Barat', 'Jawa Barat'),
    ('DKI Jakarta', 'DKI Jakarta'),
    ('Jawa Tengah', 'Jawa Tengah'),
    ('Daerah Istimewa Yogyakarta', 'Daerah Istimewa Yogyakarta'),
    ('Jawa Timur', 'Jawa Timur'),
    ('Bali', 'Bali'),
    ('Nusa Tenggara Barat', 'Nusa Tenggara Barat'),
    ('Kalimantan Barat', 'Kalimantan Barat'),
    ('Kalimantan Selatan', 'Kalimantan Selatan'),
    ('Kalimantan Tengah', 'Kalimantan Tengah'),
    ('Kalimantan Timur', 'Kalimantan Timur'),
    ('Kalimantan Utara', 'Kalimantan Utara'),
    ('Gorontalo', 'Gorontalo'),
    ('Sulawesi Barat', 'Sulawesi Barat'),
    ('Sulawesi Selatan', 'Sulawesi Selatan'),
    ('Sulawesi Tengah', 'Sulawesi Tengah'),
    ('Sulawesi Tenggara', 'Sulawesi Tenggara'),
    ('Sulawesi Utara', 'Sulawesi Utara'),
    ('Maluku', 'Maluku'),
    ('Maluku Utara', 'Maluku Utara'),
    ('Papua Barat', 'Papua Barat'),
    ('Papua', 'Papua')
    ]

class formRegistKendaraan(forms.Form):
    nomor = forms.CharField(required=True)
    nama = forms.CharField(required=True)
    jenis_kendaraan = forms.CharField(required=True)
    berat_maksimum = forms.IntegerField(required=True)


class formRegistLokasi(forms.Form):
    lokasi = forms.CharField(required=True)
    provinsi = forms.ChoiceField(choices = PROVINSI)
    kabupaten_kota = forms.CharField(required=True)
    kecamatan = forms.CharField(required=True)
    keluarahan =  forms.CharField(required=True)
    jalan = forms.CharField(required=True)

kevin/views.py
from django.shortcuts import redirect, render
from django.db import connection
from kevin.forms import *
from django.contrib import messages

def dictfetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def createKendaraan(request):
    message =""
    if request.method=="POST" :
        form = formRegistKendaraan(request.POST)
        if form.is_valid():
            nomor = form.cleaned_data.get('nomor')
            nama = form.cleaned_data.get('nama')
            jenis_kendaraan = form.cleaned_data.get('jenis_kendaraan')
            berat_maksimum = form.cleaned_data.get('berat_maksimum')

            with connection.cursor() as cursor :
                try :
                    cursor.execute('INSERT INTO KENDARAAN values(%s,%s,%s,%s)',[nomor,nama,jenis_kendaraan,berat_maksimum])   
                    message = "Kendaraan berhasil terdaftar"      
                except :
                    message = "Kendaraan yang anda masukan sudah terdaftar"   
        
        return redirect('kevin:readKendaraan')

    regist_kendaraan = formRegistKendaraan()

    context = {
			"create_kendaraan":regist_kendaraan, "message":message
		}

    return render(request, 'createKendaraan.html', context)


def readKendaraan(request):
    with connection.cursor() as cursor:
        admin = 'admin_1@gmail.com'
        supplier = 'supplier_1@gmail.com'
        username_pengguna = admin
        cursor.execute('SELECT username FROM ADMIN_SATGAS WHERE username =%s',[username_pengguna])
        isboolAdmin = cursor.fetchall()
        cursor.execute('SELECT username FROM SUPPLIER WHERE username =%s',[username_pengguna])
        isboolSupplier = cursor.fetchall()

        if(len(isboolAdmin)):
            cursor.execute('SELECT * FROM KENDARAAN k')
            role = 1

        daftar = cursor.fetchall()
        print(daftar)
        context ={'daftar':daftar, 'role':role}
        row = dictfetchall(cursor)
        return render(request,'readKendaraan.html',context)

def deleteKendaraan(request, delete_id):
    with connection.cursor() as cursor:
        cursor.execute('DELETE FROM KENDARAAN WHERE nomor = %s',[delete_id])
        return redirect('kevin:readKendaraan')

def updateKendaraan(request, update_id):
    message=""
    with connection.cursor() as cursor:
        if request.method == "POST" :
            form = formRegistKendaraan(request.POST)
            if form.is_valid():
                nomor = form.cleaned_data.get('nomor')
                nama = form.cleaned_data.get('nama')
                jenis_kendaraan = form.cleaned_data.get('jenis_kendaraan')
                berat_maksimum = form.cleaned_data.get('berat_maksimum')

                delete_kendaraan = "DELETE FROM KENDARAAN WHERE nomor =%s "
                tuple_query = [update_id]
                cursor.execute(delete_kendaraan, tuple_query)

                insert_kendaraan = 'INSERT INTO KENDARAAN VALUES(%s,%s,%s,%s)'
                tuple_query = [nomor,nama,jenis_kendaraan,berat_maksimum]
                cursor.execute(insert_kendaraan,tuple_query)

                message = "Kendaraan telah di-update"
            
        regist_kendaraan = formRegistKendaraan()

        context = {
                "update_kendaraan":regist_kendaraan , 
                "update_id" : update_id,
                "message" : message
            }

        return render(request, 'updateKendaraan.html', context )

def createLokasi(request):
    message =""
    if request.method=="POST" :
        form = formRegistLokasi(request.POST)
        if form.is_valid():
            lokasi = form.cleaned_data.get('lokasi')
            provinsi = form.cleaned_data.get('provinsi')
            kabupaten_kota = form.cleaned_data.get('kabupaten_kota')
            kecamatan = form.cleaned_data.get('kecamatan')
            keluarahan =  form.cleaned_data.get('keluarahan')
            jalan = form.cleaned_data.get('jalan')

            with connection.cursor() as cursor :
                try :
                    cursor.execute('INSERT INTO LOKASI values(%s,%s,%s,%s,%s,%s)',[lokasi,provinsi,kabupaten_kota,kecamatan,keluarahan,jalan])   
                    message = "Lokasi berhasil terdaftar"      
                except :
                    message = "Lokasi yang anda masukan sudah terdaftar"   
                    

    regist_lokasi = formRegistLokasi()

    context = {
			"create_lokasi":regist_lokasi, "message":message
		}

    return render(request, 'createLokasi.html', context)

def readLokasi(request):
    with connection.cursor() as cursor:
        admin = 'admin_1@gmail.com'
        supplier = 'supplier_1@gmail.com'
        username_pengguna = admin
        cursor.execute('SELECT username FROM ADMIN_SATGAS WHERE username =%s',[username_pengguna])
        isboolAdmin = cursor.fetchall()
        cursor.execute('SELECT username FROM SUPPLIER WHERE username =%s',[username_pengguna])
        isboolSupplier = cursor.fetchall()

        if(len(isboolAdmin)):
            cursor.execute('SELECT * FROM LOKASI')
            role = 1
       
        daftar = cursor.fetchall()
        print(daftar)
        context ={'daftar':daftar, 'role':role}
        row = dictfetchall(cursor)
        return render(request,'readLokasi.html',context)

def deleteLokasi(request, delete_id):
    with connection.cursor() as cursor:
        cursor.execute('DELETE FROM LOKASI WHERE Id = %s',[delete_id])
        return redirect('kevin:readLokasi')

def updateLokasi(request, update_id):
    message=""
    with connection.cursor() as cursor:
        if request.method == "POST" :
            form = formRegistLokasi(request.POST)
            if form.is_valid():
                lokasi = form.cleaned_data.get('lokasi')
                provinsi = form.cleaned_data.get('provinsi')
                kabupaten_kota = form.cleaned_data.get('kabupaten_kota')
                kecamatan = form.cleaned_data.get('kecamatan')
                keluarahan =  form.cleaned_data.get('keluarahan')
                jalan = form.cleaned_data.get('jalan')

                delete_lokasi = "DELETE FROM LOKASI WHERE id =%s "
                tuple_query = [update_id]
                cursor.execute(delete_lokasi, tuple_query)

                insert_lokasi = 'INSERT INTO LOKASI values(%s,%s,%s,%s,%s,%s)'
                tuple_query = [lokasi,provinsi,kabupaten_kota,kecamatan,keluarahan,jalan]   
                cursor.execute(insert_lokasi,tuple_query)
                message = "Lokasi telah diupdate" 
            
        regist_lokasi = formRegistLokasi()

        context = {
                "update_lokasi":regist_lokasi, 
                "update_id" : update_id,
                "message" : message
            }

        return render(request, 'updateLokasi.html', context )


def createBatchPengiriman(request):
    with connection.cursor() as cursor:
        admin = 'admin_1@gmail.com'
        supplier = 'supplier_1@gmail.com'
        username_pengguna = admin
        cursor.execute('SELECT username FROM ADMIN_SATGAS WHERE username =%s',[username_pengguna])
        isboolAdmin = cursor.fetchall()
        cursor.execute('SELECT username FROM SUPPLIER WHERE username =%s',[username_pengguna])
        isboolSupplier = cursor.fetchall()

        if(len(isboolAdmin)):
            cursor.execute('SELECT R.Nomor_permohonan , P.Username_petugas_faskes , F.Id_lokasi , S.Total_berat , R.Kode_status_permohonan , I.Kode_status_batch_pengiriman  FROM RIWAYAT_STATUS_PERMOHONAN R  '+
                            'LEFT JOIN PERMOHONAN_SUMBER_DAYA_FASKES P '+
                            'ON R.Nomor_permohonan = P.No_transaksi_sumber_daya ' +
                            'LEFT JOIN TRANSAKSI_SUMBER_DAYA S '+
                            'ON S.Nomor = P.No_transaksi_sumber_daya ' +
                            'LEFT JOIN FASKES F '+
                            'ON P.Username_petugas_faskes = F.Username_petugas '+
                            'LEFT JOIN BATCH_PENGIRIMAN B '+
                            'ON B.nomor_transaksi_sumber_daya = S.Nomor ' +
                            'LEFT JOIN RIWAYAT_STATUS_PENGIRIMAN I '+
                            'ON B.kode = I.Kode_batch ' )
            role = 1
       
        daftar = cursor.fetchall()
        print(daftar)
        context ={'daftar':daftar, 'role':role}
        row = dictfetchall(cursor)
        return render(request,'createBatchPengiriman.html',context)

kevin/templates/createBatchPengiriman.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
    <h1 style="text-align: center;">List Batch</h1>
    <table class="table table-border">
        <tr>
            <td>
                Nomor Transaksi
            </td>
            <td>
                Petugas Faskes
            </td>
            <td>
                Faskes
            </td>
            <td>
                Total_berat
            </td>
            <td>
                Status Permohonan
            </td>
            <td>
                Status Batch
            </td>
            
        </tr>
        {% for elem in daftar %}
        <tr>
            <td>TREQ{{ elem.0 }}</td>   
            <td>{{ elem.1 }}</td>   
            <td>{{ elem.2 }}</td>   
            <td>{{ elem.3 }}</td>  
            <td>{{ elem.4 }}</td> 
            <td>{{ elem.5 }}</td>   
            <td>
                {% if role == 1 %}
                    {% if elem.4 == "PRO" %}
                        <a href="{% url 'kevin:updateKendaraan' update_id=elem.0 %}" value="create" type="submit" class="btn border-dark">Buat Batch</a>
                    {% endif %}
                    
                    {% if elem.4 == "FIN" or elem.4 == "MAS" %}
                        <a href="{% url 'kevin:deleteKendaraan' delete_id=elem.0 %}" value="dtail" type="submit" class="btn border-dark">Detail</a>
                    {% endif %}

                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>

    {% if role == 1 %}
    <center>
    <a href="{% url 'kevin:createKendaraan' %}" name="button" value="riwayat_status" type="submit" class="btn border-dark"">Tambah</a></br></br>
    </center>
    {% endif %}


</body>
</html>

kevin/templates/createKendaraan.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create_Kendaraan</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>

    <!-- Jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <style>
        body {
            margin: 1em;
        }
    </style>
</head>

<body>
    <h1 style="text-align: center;">Create Kendaraan</h1>
    <form method="POST" class="form-control" action="{% url 'kevin:createKendaraan' %}"> 
    {% csrf_token %}

    <table class="col-md-9 p-0 mx-auto">
        {{create_kendaraan.as_table}}
    </table>
    <center><button type="submit">SIMPAN</button></center>
    </form>
    {{message}}


</body>
</html>

kevin/templates/createLokasi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 style="text-align: center;">Create Lokasi</h1>
    <form method="POST" class="form-control" action="{% url 'kevin:createLokasi' %}"> 
    {% csrf_token %}

    <table class="col-md-9 p-0 mx-auto">
        {{create_lokasi.as_table}}
    </table>
    <button type="submit">SUBMIT</button>
    </form>
    {{message}}


</body>
</html>

kevin/templates/readKendaraan.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
    <h1 style="text-align: center;">List Kendaraan</h1>
    <table class="table table-border">
        <tr>
            <td>
                Nomor
            </td>
            <td>
                Nama
            </td>
            <td>
                Jenis_kendaraan
            </td>
            <td>
                Berat_maksimum (kg)
            </td>
            
        </tr>
        {% for elem in daftar %}
        <tr>
            <td>{{ elem.0 }}</td>   
            <td>{{ elem.1 }}</td>   
            <td>{{ elem.2 }}</td>   
            <td>{{ elem.3 }}</td>  
            <td>
                {% if role == 1 %}
                    <a href="{% url 'kevin:updateKendaraan' update_id=elem.0 %}" value="update" type="submit" class="btn border-dark">Update</a>
                    <a href="{% url 'kevin:deleteKendaraan' delete_id=elem.0 %}" name="button" value="delete" type="submit" class="btn border-dark">Delete</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>

    {% if role == 1 %}
    <center>
    <a href="{% url 'kevin:createKendaraan' %}" name="button" value="riwayat_status" type="submit" class="btn border-dark"">Tambah</a></br></br>
    </center>
    {% endif %}


</body>
</html>

kevin/templates/readLokasi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
    <h1 style="text-align: center;">List Lokasi</h1>
    <table class="table table-border">
        <tr>
            <td>
                Lokasi
            </td>
            <td>
                Provinsi
            </td>
            <td>
                Kabupaten/Kota
            </td>
            <td>
                Kecamatan
            </td>
            <td>
                Kelurahan
            </td>
            <td>
                Jalan
            </td>
            
        </tr>
        {% for elem in daftar %}
        <tr>
            <td>{{ elem.0 }}</td>   
            <td>{{ elem.1 }}</td>   
            <td>{{ elem.2 }}</td>   
            <td>{{ elem.3 }}</td>  
            <td>{{ elem.4 }}</td>  
            <td>{{ elem.5 }}</td>  
            <td>
                {% if role == 1 %}
                    <a href="{% url 'kevin:updateLokasi' update_id=elem.0 %}" value="update" type="submit" class="btn border-dark">Update</a>
                    <a href="{% url 'kevin:deleteLokasi' delete_id=elem.0 %}" name="button" value="delete" type="submit" class="btn border-dark">Delete</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>

    {% if role == 1 %}
    <center>
    <a href="{% url 'kevin:createLokasi' %}" name="button" value="riwayat_status" type="submit" class="btn border-dark"">Tambah</a></br></br>
    </center>
    {% endif %}


</body>
</html>

kevin/templates/updateKendaraan.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 style="text-align: center;">Ubah Data Kendaraan</h1>
    <form method="POST" class="form-control" action="{% url 'kevin:updateKendaraan' update_id %}"> 
    {% csrf_token %}

    <table class="col-md-9 p-0 mx-auto">
        {{update_kendaraan.as_table}}
    </table>
    <button type="submit">SUBMIT</button>
    </form>
    {{message}}

</body>
</html>

kevin/templates/updateLokasi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 style="text-align: center;">Update Lokasi</h1>
    <form method="POST" class="form-control" action="{% url 'kevin:updateLokasi' update_id %}"> 
    {% csrf_token %}

    <table class="col-md-9 p-0 mx-auto">
        {{update_lokasi.as_table}}
    </table>
    <button type="submit">SUBMIT</button>
    </form>
    {{message}}


</body>
</html>