TK4_E11/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('',include('gilangcy.urls')),
    path('',include('kevin.urls')),
    path('', include('alishayb.urls', namespace="alishayb")),
    path('', include('dodo.urls', namespace="dodo"))
]

alishayb/urls.py
from django.urls import path
from . import views

app_name = 'alishayb'

urlpatterns = [
    path('createPermohonanSumberDaya/', views.create_transaksi_sumber_daya, name="create_transaksi_sumber_daya"),
    path('createDaftarItem/<int:no_transaksi>/', views.create_permohonan_sumber_daya, name="create_permohonan_sumber_daya"),
    path('readPermohonanSumberDaya/', views.read_permohonan_sumber_daya, name="read_permohonan_sumber_daya"),
    path('deletePermohonanSumberDaya/<int:no_transaksi>/', views.delete_permohonan_sumber_daya, name="delete_permohonan_sumber_daya"),
    path('detailPermohonanSumberDaya/<int:no_transaksi>/', views.detail_permohonan_sumber_daya, name="detail_permohonan_sumber_daya"),
    path('updatePermohonanSumberDaya/<int:no_transaksi>/', views.update_permohonan_sumber_daya, name="update_permohonan_sumber_daya"),

    # change status
    path('prosesPermohonan/<int:no_transaksi>/', views.proses_permohonan, name="proses_permohonan"),
    path('tolakPermohonan/<int:no_transaksi>/', views.tolak_permohonan, name="reject_permohonan"),
    path('selesaiPermohonanDenganMasalah/<int:no_transaksi>/', views.selesai_permohonan_dengan_masalah, name="selesai_permohonan_dengan_masalah"),
    path('selesaiPermohonan/<int:no_transaksi>/', views.selesai_permohonan, name="selesai_permohonan"),

    # riwayat status
    path('riwayatStatusPermohonan/<int:no_transaksi>/', views.riwayat_status_permohonan, name="riwayat_status_permohonan"),

    path('createItemSumberDaya/', views.create_item_sumber_daya, name="create_item_sumber_daya"),
    path('readItemSumberDaya/', views.read_item_sumber_daya, name="read_item_sumber_daya"),
    path('updateItemSumberDaya/<str:kode_item>/', views.update_item_sumber_daya, name="update_item_sumber_daya"),
    path('deleteItemSumberDaya/<str:kode_item>/', views.delete_item_sumber_daya, name="delete_item_sumber_daya"),
]

dodo/urls.py
from django.urls import path
from . import views

app_name = "dodo"

urlpatterns = [
    path('get-lokasi-alamat/<slug:id_lokasi>', views.locationIDToAddressEndpoint, name="locationIDToAddressEndpoint"),
    path('get-faskes-tipe/<slug:id_tipe>', views.faskesCodeToTypeNameEndpoint, name="faskesCodeToTypeNameEndpoint"),
    path('list-faskes/', views.readFaskes, name="readFaskes"),
    path('delete-faskes/<slug:kode_faskes>', views.deleteFaskes, name="deleteFaskes"),
    path('update-faskes/<slug:kode_faskes>', views.updateFaskes, name="updateFaskes"),
    path('create-faskes/', views.createFaskes, name="createFaskes")
]

gilangcy/urls.py
from django.urls import path
from . import views

app_name = 'gilangcy'

urlpatterns = [
    path('createPesananSumberDaya/', views.createPesananSumberDaya, name='createPesananSumberDaya'),
    path('readPesananSumberDaya/',views.readPesananSumberDaya, name='readPesananSumberDaya'),
    path('deletePesananSumberDaya/<int:delete_id>/',views.deletePesananSumberDaya, name='deletePesananSumberDaya'),
    path('detailPesananSumberDaya/<int:detail_id>/',views.detailPesananSumberDaya, name='detailPesananSumberDaya'),
    path('riwayatStatusPesananSumberDaya/<int:pesanan_id>/',views.riwayatStatusPesananSumberDaya, name='riwayatStatusPesananSumberDaya'),
    path('updatePesananSumberDaya/<int:pesanan_id>/',views.updatePesananSumberDaya, name='updatePesananSumberDaya'),
    path('createRiwayatStatusPesanan/<int:pesanan_id>/<str:kode>',views.createRiwayatStatusPesanan, name='createRiwayatStatusPesanan'),
    path('readStokFaskes/',views.readStokFaskes, name='readStokFaskes'),
    path('createStokFaskes/',views.createStokFaskes, name='createStokFaskes'),
    path('deleteStokFaskes/<str:kode_faskes>/<str:item>',views.deleteStokFaskes, name='deleteStokFaskes'),
    path('updateStokFaskes/<str:kode_faskes>/<str:item>',views.updateStokFaskes, name='updateStokFaskes')
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register',views.register,name='register'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('daftarAdminSatgas/', views.daftar_admin_satgas, name='daftar_admin_satgas'),
    path('daftarPetugasFaskes/', views.daftar_petugas_faskes, name='daftar_petugas_faskes'),
    path('daftarSupplier/', views.daftar_supplier, name='daftar_supplier'),
    path('daftarPetugasDistribusi/', views.daftar_petugas_distribusi, name='daftar_petugas_distribusi')

]

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms

class formLogin(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(widget=forms.PasswordInput())

class formRegistRole(forms.Form):
    ROLE_1 = 'Admin Satgas'
    ROLE_2 = 'Supplier'
    ROLE_3 = 'Petugas Distribusi'
    ROLE_4 = 'Petugas Faskes'
    ROLE = (
		(ROLE_1, 'Admin Satgas'),
		(ROLE_2, 'Supplier'),
		(ROLE_3, 'Petugas Distribusi'),
        (ROLE_4, 'Petugas Faskes'),
	)
    role = forms.ChoiceField(choices=ROLE)

PROVINSI= [
    ('Aceh', 'Aceh'),
    ('Sumatra Utara', 'Sumatra Utara'),
    ('Sumatra Barat', 'Sumatra Barat'),
    ('Riau', 'Riau'),
    ('Kepulauan Riau', 'Kepulauan Riau'),
    ('Jambi', 'Jambi'),
    ('Bengkulu', 'Bengkulu'),
    ('Sumatra Selatan', 'Sumatra Selatan'),
    ('Kepulauan Bangka Belitung', 'Kepulauan Bangka Belitung'),
    ('Lampung', 'Lampung'),
    ('Banten', 'Banten'),
    ('Jawa Barat', 'Jawa Barat'),
    ('DKI Jakarta', 'DKI Jakarta'),
    ('Jawa Tengah', 'Jawa Tengah'),
    ('Daerah Istimewa Yogyakarta', 'Daerah Istimewa Yogyakarta'),
    ('Jawa Timur', 'Jawa Timur'),
    ('Bali', 'Bali'),
    ('Nusa Tenggara Barat', 'Nusa Tenggara Barat'),
    ('Kalimantan Barat', 'Kalimantan Barat'),
    ('Kalimantan Selatan', 'Kalimantan Selatan'),
    ('Kalimantan Tengah', 'Kalimantan Tengah'),
    ('Kalimantan Timur', 'Kalimantan Timur'),
    ('Kalimantan Utara', 'Kalimantan Utara'),
    ('Gorontalo', 'Gorontalo'),
    ('Sulawesi Barat', 'Sulawesi Barat'),
    ('Sulawesi Selatan', 'Sulawesi Selatan'),
    ('Sulawesi Tengah', 'Sulawesi Tengah'),
    ('Sulawesi Tenggara', 'Sulawesi Tenggara'),
    ('Sulawesi Utara', 'Sulawesi Utara'),
    ('Maluku', 'Maluku'),
    ('Maluku Utara', 'Maluku Utara'),
    ('Papua Barat', 'Papua Barat'),
    ('Papua', 'Papua')
    ]


class formRegistAdminSatgas(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(widget=forms.PasswordInput())
    nama_lengkap = forms.CharField(required=True)
    alamat_kelurahan = forms.CharField()
    alamat_kecamatan = forms.CharField()
    alamat_kota = forms.CharField()
    provinsi = forms.ChoiceField(choices = PROVINSI)
    no_telp = forms.IntegerField()


class formRegistSupplier(forms.Form):
    nama_organisasi = forms.CharField(required=True)
    username = forms.CharField(required=True)
    password = forms.CharField(widget=forms.PasswordInput())
    nama_lengkap = forms.CharField(required=True)
    alamat_kelurahan = forms.CharField()
    alamat_kecamatan = forms.CharField()
    alamat_kota = forms.CharField()
    provinsi = forms.ChoiceField(choices = PROVINSI)
    no_telp = forms.IntegerField()

class formRegistPetugasDistribusi(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(widget=forms.PasswordInput())
    nama_lengkap = forms.CharField(required=True)
    alamat_kelurahan = forms.CharField()
    alamat_kecamatan = forms.CharField()
    alamat_kota = forms.CharField()
    provinsi = forms.ChoiceField(choices = PROVINSI)
    no_telp = forms.IntegerField()
    no_sim = forms.IntegerField()

class formRegistPetugasFaskes(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(widget=forms.PasswordInput())
    nama_lengkap = forms.CharField(required=True)
    alamat_kelurahan = forms.CharField()
    alamat_kecamatan = forms.CharField()
    alamat_kota = forms.CharField()
    provinsi = forms.ChoiceField(choices = PROVINSI)
    no_telp = forms.IntegerField()

user/views.py
from django.shortcuts import redirect, render
from django.db import connection
from user.forms import *
from django.db.utils import InternalError
from django.contrib import messages

# Create your views here.

def dictfetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def login(request):
    if request.method == 'POST':
        form = formLogin(request.POST)
        if form.is_valid():     
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            with connection.cursor() as cursor:
                cursor.execute(f"SELECT username FROM pengguna WHERE username='{username}' AND password='{password}'")
                user_data = cursor.fetchone()

                if user_data is not None:
                    request.session['username'] = username
                    request.session['role'] = getRole(username)

                    return redirect('user:dashboard')
                else:
                    form = formLogin()
                    context = {
                        'login_form' : form,
                        'message' : 'Incorrect username or password. Please try again.'
                    }
                    return render(request, 'login.html', context)

    form = formLogin()
    context = {
        'login_form' : form
    }
    return render(request, 'login.html', context)

def getRole(username):
    with connection.cursor() as cursor:
        cursor.execute(f"SELECT username FROM admin_satgas WHERE username='{username}'")
        role = cursor.fetchone()

        if role is not None:
            return 'Admin Satgas'

        cursor.execute(f"SELECT username FROM petugas_faskes WHERE username='{username}'")
        role = cursor.fetchone()

        if role is not None:
            return 'Petugas Faskes'
        
        cursor.execute(f"SELECT username FROM supplier WHERE username='{username}'")
        role = cursor.fetchone()

        if role is not None:
            return 'Supplier'

        cursor.execute(f"SELECT username FROM petugas_distribusi WHERE username='{username}'")
        role = cursor.fetchone()

        if role is not None:
            return 'Petugas Distribusi'

    return 'Unknown'

def logout(request):
    request.session.flush()
    context = {
        'message' : 'Logout berhasil.'
    }
    return render(request, 'welcome.html', context)

def register(request):
    return render(request, 'register.html')

def welcome(request):
    return render(request, 'welcome.html')

def dashboard(request):
    role = request.session['role']
    username = request.session['username']
    context = {'role':role,'username':username}
    print(role)
    return render(request,'dashboard.html',context)

def daftar_admin_satgas(request):
    if request.method=="POST" :
        form = formRegistAdminSatgas(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            nama_lengkap = form.cleaned_data.get('nama_lengkap')
            alamat_kelurahan = form.cleaned_data.get('alamat_kelurahan')
            alamat_kecamatan = form.cleaned_data.get('alamat_kecamatan')
            alamat_kota = form.cleaned_data.get('alamat_kota')
            provinsi = form.cleaned_data.get('provinsi')
            no_telp = form.cleaned_data.get('no_telp')

            with connection.cursor() as cursor:
                try:
                    cursor.execute('INSERT INTO PENGGUNA values(%s,%s,%s,%s,%s,%s,%s,%s)',[username,password,nama_lengkap,alamat_kelurahan,alamat_kecamatan,alamat_kota,provinsi,no_telp])  
                    cursor.execute('INSERT INTO ADMIN_SATGAS values(%s)',[username])
                    
                    request.session['username']=username
                    request.session['role'] = 'Admin Satgas'
                    return redirect('user:dashboard')
                except(InternalError):
                    messages.error(request, "Username sudah terdaftar!")
                    return redirect('user:daftar_admin_satgas')

    context = {
        "create_admin_satgas": formRegistAdminSatgas()
    }
    return render(request, 'daftar_admin_satgas.html', context)

def daftar_petugas_faskes(request):
    if request.method=="POST" :
        form = formRegistPetugasFaskes(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            nama_lengkap = form.cleaned_data.get('nama_lengkap')
            alamat_kelurahan = form.cleaned_data.get('alamat_kelurahan')
            alamat_kecamatan = form.cleaned_data.get('alamat_kecamatan')
            alamat_kota = form.cleaned_data.get('alamat_kota')
            provinsi = form.cleaned_data.get('provinsi')
            no_telp = form.cleaned_data.get('no_telp')

            with connection.cursor() as cursor:
                try:
                    cursor.execute('INSERT INTO PENGGUNA values(%s,%s,%s,%s,%s,%s,%s,%s)',[username,password,nama_lengkap,alamat_kelurahan,alamat_kecamatan,alamat_kota,provinsi,no_telp])  
                    cursor.execute('INSERT INTO PETUGAS_FASKES values(%s)',[username])
                    
                    request.session['username']=username
                    request.session['role'] = 'Petugas Faskes'
                    return redirect('user:dashboard')
                except(InternalError):
                    messages.error(request, "Username sudah terdaftar!")
                    return redirect('user:daftar_petugas_faskes')

    context = {
        "create_petugas_faskes": formRegistPetugasFaskes()
    }
    return render(request, 'daftar_petugas_faskes.html', context)

def daftar_supplier(request):
    if request.method=="POST" :
        form = formRegistSupplier(request.POST)
        if form.is_valid():
            nama_organisasi = form.cleaned_data.get('nama_organisasi')
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            nama_lengkap = form.cleaned_data.get('nama_lengkap')
            alamat_kelurahan = form.cleaned_data.get('alamat_kelurahan')
            alamat_kecamatan = form.cleaned_data.get('alamat_kecamatan')
            alamat_kota = form.cleaned_data.get('alamat_kota')
            provinsi = form.cleaned_data.get('provinsi')
            no_telp = form.cleaned_data.get('no_telp')

            with connection.cursor() as cursor:
                try:
                    cursor.execute('INSERT INTO PENGGUNA values(%s,%s,%s,%s,%s,%s,%s,%s)',[username,password,nama_lengkap,alamat_kelurahan,alamat_kecamatan,alamat_kota,provinsi,no_telp])  
                    cursor.execute('INSERT INTO supplier values(%s,%s)',[username,nama_organisasi])

                    request.session['username']=username
                    request.session['role'] = 'Supplier'
                    return redirect('user:dashboard')
                except(InternalError):
                    messages.error(request, "Username sudah terdaftar!")
                    return redirect('user:daftar_supplier')

    context = {
        "create_supplier": formRegistSupplier()
        }
    return render(request, 'daftar_supplier.html', context)

def daftar_petugas_distribusi(request):
    if request.method=="POST" :
        form = formRegistPetugasDistribusi(request.POST)
        if form.is_valid():
            no_sim = form.cleaned_data.get('no_sim')
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            nama_lengkap = form.cleaned_data.get('nama_lengkap')
            alamat_kelurahan = form.cleaned_data.get('alamat_kelurahan')
            alamat_kecamatan = form.cleaned_data.get('alamat_kecamatan')
            alamat_kota = form.cleaned_data.get('alamat_kota')
            provinsi = form.cleaned_data.get('provinsi')
            no_telp = form.cleaned_data.get('no_telp')

            with connection.cursor() as cursor:
                try:
                    cursor.execute('INSERT INTO PENGGUNA values(%s,%s,%s,%s,%s,%s,%s,%s)',[username,password,nama_lengkap,alamat_kelurahan,alamat_kecamatan,alamat_kota,provinsi,no_telp])  
                    cursor.execute('INSERT INTO PETUGAS_DISTRIBUSI values(%s,%s)',[username,no_sim])

                    request.session['username']=username
                    request.session['role'] = 'Petugas Distribusi'
                    return redirect('user:dashboard')
                except(InternalError):
                    messages.error(request, "Username sudah terdaftar!")
                    return redirect('user:daftar_petugas_distribusi')

    context = {
        "create_petugas_distribusi": formRegistPetugasDistribusi()
        }
    return render(request, 'daftar_petugas_distribusi.html', context)

user/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <style>
        body {
            margin: 1em;
        }
        h2{
            width:fit-content;
        }
        .btn{
            margin-bottom: 0.5em;
        }

    </style>
</head>

<body>
    <h2 class='mx-auto'> Dashboard</h2>
    <a href="{% url 'user:logout' %}" type="button" class="mx-auto btn btn-primary">Logout</a><br>
    <b>Role = {{role}}</b><br>
    <b>Username = {{username}}</b> <br>
    {% if role == 'Admin Satgas' %}
    <div>
        <b>PROFIL</b> <br>
        <a href="#" class="btn btn-outline-primary">1. Update Profil</a>
    </div>
    <div>
        <b>PERMOHONAN SUMBER DAYA</b><br>
        <a href="{% url 'alishayb:read_permohonan_sumber_daya' %}" class="btn btn-outline-primary">1. List Permohonan Sumber Daya</a><br>
        <a href="{% url 'alishayb:read_permohonan_sumber_daya' %}" class="btn btn-outline-primary">2. Buat Riwayat Status Permohonan Sumber Daya</a><br>
        <a href="{% url 'alishayb:read_permohonan_sumber_daya' %}" class="btn btn-outline-primary">3. List Riwayat Status Permohonan Sumber Daya</a>
    </div>
    <div>
        <b>ITEM SUMBER DAYA</b> <br>
        <a href="{% url 'alishayb:read_item_sumber_daya' %}" class="btn btn-outline-primary">1. List Item Sumber Daya</a>
    </div>
    <div>
        <b>PESANAN SUMBER DAYA</b><br>
        <a href="{% url 'gilangcy:createPesananSumberDaya' %}" class="btn btn-outline-primary">1. Buat Pesanan Sumber Daya</a><br>
        <a href="{% url 'gilangcy:readPesananSumberDaya' %}" class="btn btn-outline-primary">2. List Pesanan Sumber Daya</a><br>
        <a href="{% url 'gilangcy:readPesananSumberDaya' %}" class="btn btn-outline-primary">3. List Riwayat Status Pesanan Sumber Daya</a>
    </div>
    <div>
        <b>KENDARAAN</b><br>
        <a href="#" class="btn btn-outline-primary">1. Buat Kendaraan</a><br>
        <a href="#" class="btn btn-outline-primary">2. List Kendaraan</a><br>
    </div>
    <div>
        <b>BATCH PENGIRIMAN</b><br>
        <a href="#" class="btn btn-outline-primary">1. Buat Batch Pengiriman</a><br>
        <a href="#" class="btn btn-outline-primary">2. List Batch Pengiriman</a><br>
        <a href="#" class="btn btn-outline-primary">3. Buat Riwayat Status Batch Pengiriman</a><br>
        <a href="#" class="btn btn-outline-primary">4. List Riwayat Status Batch Pengiriman</a>
    </div>
    <div>
        <b>LOKASI</b> <br>
        <a href="#" class="btn btn-outline-primary">1. Buat Lokasi</a><br>
        <a href="#" class="btn btn-outline-primary">2. List Lokasi</a><br>
    </div>
    <div>
        <b>FASILITAS KESEHATAN</b> <br>
        <a href="{% url 'dodo:createFaskes' %}" class="btn btn-outline-primary">1. Buat Faskes</a><br>
        <a href="{% url 'dodo:readFaskes' %}" class="btn btn-outline-primary">2. List Faskes</a><br>
        <a href="{% url 'gilangcy:createStokFaskes' %}" class="btn btn-outline-primary">3. Buat Stock Faskes</a><br>
        <a href="{% url 'gilangcy:readStokFaskes' %}" class="btn btn-outline-primary">4. List Stock Faskes</a>
    </div>
    <div>
        <b>WAREHOUSE SATGAS</b> <br>
        <a href="#" class="btn btn-outline-primary">1. Buat Warehouse Satgass</a><br>
        <a href="#" class="btn btn-outline-primary">2. List Warehouse Satgas</a><br>
        <a href="#" class="btn btn-outline-primary">3. Buat Stock Warehouse Satgas</a><br>
        <a href="#" class="btn btn-outline-primary">4. List Stock Warehouse Satgas</a>
    </div>
    {% elif role == 'Supplier' %}
    <div>
        <b>PROFIL</b> <br>
        <a href="#" class="btn btn-outline-primary">1. Update Profil</a>
    </div>
    <div>
        <b>ITEM SUMBER DAYA</b> <br>
        <a href="{% url 'alishayb:create_item_sumber_daya' %}" class="btn btn-outline-primary">1. Buat Item Sumber Daya</a> <br>
        <a href="{% url 'alishayb:read_item_sumber_daya' %}" class="btn btn-outline-primary">2. List Item Sumber Daya</a>
    </div>
    <div>
        <b>PESANAN SUMBER DAYA</b><br>
        <a href="{% url 'gilangcy:readPesananSumberDaya' %}" class="btn btn-outline-primary">1. List Pesanan Sumber Daya</a><br>
        <a href="{% url 'gilangcy:readPesananSumberDaya' %}" class="btn btn-outline-primary">2. Ubah Riwayat Status Pesanan Sumber Daya</a><br>
        <a href="{% url 'gilangcy:readPesananSumberDaya' %}" class="btn btn-outline-primary">3. List Riwayat Status Pesanan Sumber Daya</a>
    </div>
    <div>
        <b>FASILITAS KESEHATAN</b> <br>
        <a href="{% url 'dodo:readFaskes' %}" class="btn btn-outline-primary">1. List Faskes</a><br>
    </div>
    <div>
       <b>WAREHOUSE SATGAS</b> <br>
        <a href="#" class="btn btn-outline-primary">1. List Warehouse Satgas</a><br>
        <a href="#" class="btn btn-outline-primary">2. List Stock Warehouse Satgas</a>
    </div>
    {% elif role == 'Petugas Faskes' %}
    <div>
        <b>PROFIL</b> <br>
        <a href="#" class="btn btn-outline-primary">1. Update Profil</a>
    </div>
    <div>
        <b>PERMOHONAN SUMBER DAYA</b><br>
        <a href="{% url 'alishayb:create_transaksi_sumber_daya' %}" class="btn btn-outline-primary">1. Buat Permohonan Sumber Daya</a><br>
        <a href="{% url 'alishayb:read_permohonan_sumber_daya' %}" class="btn btn-outline-primary">2. List Permohonan Sumber Daya</a><br>
        <a href="{% url 'alishayb:read_permohonan_sumber_daya' %}" class="btn btn-outline-primary">3. List Riwayat Status Permohonan Sumber Daya</a>
    </div>
    <div>
        <b>FASILITAS KESEHATAN</b> <br>
        <a href="{% url 'gilangcy:readStokFaskes' %}" class="btn btn-outline-primary">1. List Stock Faskes</a>
    </div>
    <div>
        <b>WAREHOUSE SATGAS</b> <br>
        <a href="#" class="btn btn-outline-primary">1. List Stock Warehouse Satgas</a>
    </div>
    <div>
        <b>BATCH PENGIRIMAN</b><br>
        <a href="#" class="btn btn-outline-primary">1. List Batch Pengiriman</a><br>
    </div>
    {% elif role == 'Petugas Distribusi' %}
    <div>
        <b>PROFIL</b> <br>
        <a href="#" class="btn btn-outline-primary">1. Update Profil</a>
    </div>
    <div>
        <b>KENDARAAN</b><br>
        <a href="#" class="btn btn-outline-primary">1. List Kendaraan</a><br>
    </div>
    <div>
        <b>BATCH PENGIRIMAN</b><br>
        <a href="#" class="btn btn-outline-primary">1. List Batch Pengiriman</a><br>
        <a href="#" class="btn btn-outline-primary">2. List Riwayat Status Batch Pengiriman</a>
    </div>
    {% endif %}
</body>
</html>