TK4_E11/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('',include('gilangcy.urls')),
    path('',include('kevin.urls')),
    path('', include('alishayb.urls', namespace="alishayb")),
    path('', include('dodo.urls', namespace="dodo"))
]

alishayb/urls.py
from django.urls import path
from . import views

app_name = 'alishayb'

urlpatterns = [
    path('createPermohonanSumberDaya/', views.create_transaksi_sumber_daya, name="create_transaksi_sumber_daya"),
    path('createDaftarItem/<int:no_transaksi>/', views.create_permohonan_sumber_daya, name="create_permohonan_sumber_daya"),
    path('readPermohonanSumberDaya/', views.read_permohonan_sumber_daya, name="read_permohonan_sumber_daya"),
    path('deletePermohonanSumberDaya/<int:no_transaksi>/', views.delete_permohonan_sumber_daya, name="delete_permohonan_sumber_daya"),
    path('detailPermohonanSumberDaya/<int:no_transaksi>/', views.detail_permohonan_sumber_daya, name="detail_permohonan_sumber_daya"),
    path('updatePermohonanSumberDaya/<int:no_transaksi>/', views.update_permohonan_sumber_daya, name="update_permohonan_sumber_daya"),

    # change status
    path('prosesPermohonan/<int:no_transaksi>/', views.proses_permohonan, name="proses_permohonan"),
    path('tolakPermohonan/<int:no_transaksi>/', views.tolak_permohonan, name="reject_permohonan"),
    path('selesaiPermohonanDenganMasalah/<int:no_transaksi>/', views.selesai_permohonan_dengan_masalah, name="selesai_permohonan_dengan_masalah"),
    path('selesaiPermohonan/<int:no_transaksi>/', views.selesai_permohonan, name="selesai_permohonan"),

    # riwayat status
    path('riwayatStatusPermohonan/<int:no_transaksi>/', views.riwayat_status_permohonan, name="riwayat_status_permohonan"),

    path('createItemSumberDaya/', views.create_item_sumber_daya, name="create_item_sumber_daya"),
    path('readItemSumberDaya/', views.read_item_sumber_daya, name="read_item_sumber_daya"),
    path('updateItemSumberDaya/<str:kode_item>/', views.update_item_sumber_daya, name="update_item_sumber_daya"),
    path('deleteItemSumberDaya/<str:kode_item>/', views.delete_item_sumber_daya, name="delete_item_sumber_daya"),
]

dodo/urls.py
from django.urls import path
from . import views

app_name = "dodo"

urlpatterns = [
    path('get-lokasi-alamat/<slug:id_lokasi>', views.locationIDToAddressEndpoint, name="locationIDToAddressEndpoint"),
    path('get-faskes-tipe/<slug:id_tipe>', views.faskesCodeToTypeNameEndpoint, name="faskesCodeToTypeNameEndpoint"),
    path('list-faskes/', views.readFaskes, name="readFaskes"),
    path('delete-faskes/<slug:kode_faskes>', views.deleteFaskes, name="deleteFaskes"),
    path('update-faskes/<slug:kode_faskes>', views.updateFaskes, name="updateFaskes"),
    path('create-faskes/', views.createFaskes, name="createFaskes")
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register',views.register,name='register'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('daftarAdminSatgas/', views.daftar_admin_satgas, name='daftar_admin_satgas'),
    path('daftarPetugasFaskes/', views.daftar_petugas_faskes, name='daftar_petugas_faskes'),
    path('daftarSupplier/', views.daftar_supplier, name='daftar_supplier'),
    path('daftarPetugasDistribusi/', views.daftar_petugas_distribusi, name='daftar_petugas_distribusi')

]

alishayb/models.py
from django.db import models

# Create your models here.

alishayb/forms.py
from django import forms
from django.db import connection

class TransaksiSumberDaya(forms.Form):
    nomor_transaksi = forms.IntegerField(widget=forms.TextInput(attrs={'disabled':'disabled'}))
    username_petugas = forms.CharField(widget=forms.TextInput(attrs={'disabled':'disabled'}))

TIPE_ITEM = [
    ('APD', 'Alat Pelindung Diri'),
    ('VEN', 'Ventilator'),
    ('BED', 'Tempat Tidur'),
    ('MSK', 'Masker'),
    ('VAK', 'Vaksin'),
    ('PCR', 'PCR Test Kit'),
    ('RAP', 'Rapid Test Kit')
]

class DaftarItem(forms.Form):
    no_urut = forms.IntegerField(widget=forms.TextInput(attrs={'disabled':'disabled'}))
    item = forms.ChoiceField(choices = TIPE_ITEM)
    jumlah_item = forms.IntegerField() 

class itemSumberDayaForm(forms.Form):
    supplier = forms.CharField(required=False)
    nama_item = forms.CharField(required=True)
    harga_satuan = forms.IntegerField(required=True)
    berat_satuan = forms.IntegerField(required=True)
    tipe_item = forms.ChoiceField(choices = TIPE_ITEM)
    

    

alishayb/views.py
from django.shortcuts import render, redirect
from alishayb.forms import *
from datetime import date
from django.http import request, JsonResponse
from django.db import connection
from django.urls import reverse
from django.contrib import messages
import json

# Create your views here.
def create_transaksi_sumber_daya(request):
    username = request.session['username']
    if request.session['role'] != 'Petugas Faskes':
        return redirect('user:welcome')
    with connection.cursor() as cursor:
        if request.method == "POST":
            form = TransaksiSumberDaya(request.POST)
            now = date.today().strftime("%Y-%m-%d")
            cursor.execute("INSERT INTO TRANSAKSI_SUMBER_DAYA(tanggal) values(\'" + now + "\')")
            cursor.execute('SELECT MAX(nomor) FROM TRANSAKSI_SUMBER_DAYA')
            tuple_no_terakhir = list(cursor.fetchone())
            no_transaksi = int(tuple_no_terakhir[0])

            return redirect('alishayb:create_permohonan_sumber_daya', no_transaksi)

        cursor.execute('SELECT MAX(nomor) FROM TRANSAKSI_SUMBER_DAYA')
        no_terakhir_permohonan = list(cursor.fetchone())
        no_transaksi_baru = int(no_terakhir_permohonan[0]) + 1

        form = TransaksiSumberDaya()
        form.fields['nomor_transaksi'].widget.attrs.update({'value': 'TREQ'+ str(no_transaksi_baru)})
        form.fields['username_petugas'].widget.attrs.update({'value': username})
        context = {
            "permohonan_sumber_daya": form
        }
        return render(request, 'create_permohonan_sumber_daya.html', context)

def create_permohonan_sumber_daya(request, no_transaksi):
    username = request.session['username']
    if request.session['role'] != 'Petugas Faskes':
        return redirect('user:welcome')
    with connection.cursor() as cursor:
        if request.method == "POST":
            no_transaksi = request.POST.get('no_transaksi')

            total_item = request.POST.get('total_item')
            daftar_item = []
            for i in range(int(total_item)):
                daftar_item.append(request.POST.getlist('list_daftar_item[' + str(i) + '][]'))

            insert_item_query = 'INSERT INTO DAFTAR_ITEM values'
            no_urut = 1
            for item in daftar_item:
                insert_item_query += f"({no_transaksi}, {no_urut}, {item[0]}, '{item[1]}'),"
                no_urut+=1
            insert_item_query = insert_item_query[:-1]
            
            catatan = request.POST.get('catatan')

            cursor.execute(insert_item_query)
            cursor.execute(f"INSERT INTO PERMOHONAN_SUMBER_DAYA_FASKES VALUES('{no_transaksi}','{username}','{catatan}')")

            data = {
                'redirecturl' : "/readPermohonanSumberDaya/"
            }

            return JsonResponse(data)

        cursor.execute('SELECT kode, nama FROM ITEM_SUMBER_DAYA')
        tipe_item = list(cursor.fetchall())
        context = {
            "daftar_item": DaftarItem(),
            "no_transaksi": no_transaksi,
            "tipe_item": tipe_item 
        }
        return render(request, 'create_daftar_item.html', context)

def read_permohonan_sumber_daya(request):
    username = request.session['username']
    role = request.session['role']
    if (role != 'Petugas Faskes') and (role != 'Admin Satgas'):
        return redirect('user:welcome')
    with connection.cursor() as cursor:
        query_filter = ""
        if role == 'Petugas Faskes':
            query_filter += f"AND PN.username='{username}' "

        cursor.execute("SELECT r.nomor_permohonan, pn.nama, MAX(r.tanggal), total_berat, total_item, catatan," + 
                        "RIGHT(string_agg(kode_status_permohonan, ' '),3) " + 
                        'FROM permohonan_with_username PN, transaksi_sumber_daya T, riwayat_status_permohonan R ' +
                        "WHERE R.nomor_permohonan = PN.no_transaksi_sumber_daya AND PN.no_transaksi_sumber_daya = T.nomor " + query_filter +
                        'GROUP BY (r.nomor_permohonan, pn.nama, total_berat, total_item, catatan) ' +
                        'ORDER BY r.nomor_permohonan')
        data_fetch = list(cursor.fetchall())
        
        list_permohonan = []
        for data in data_fetch:
            list_data = list(data)
            list_data[3] = list_data[3]/1000
            list_permohonan.append(list_data)

        context = {
            'data_permohonan' : list_permohonan,
            'role' : role
        }
        return render(request, 'read_permohonan_sumber_daya.html', context)

def delete_permohonan_sumber_daya(request, no_transaksi):
    if request.session['role'] != 'Petugas Faskes':
        return redirect('user:welcome')
    with connection.cursor() as cursor:
        cursor.execute('DELETE FROM TRANSAKSI_SUMBER_DAYA WHERE nomor=' + str(no_transaksi))
        messages.info(request, "Permohonan berhasil dihapus.")
        return redirect('alishayb:read_permohonan_sumber_daya')

def detail_permohonan_sumber_daya(request, no_transaksi):
    role = request.session['role']
    if (role != 'Petugas Faskes') and (role != 'Admin Satgas'):
        return redirect('user:welcome')
    with connection.cursor() as cursor:
        cursor.execute('SELECT DISTINCT nomor, PE.nama, tanggal, no_urut, DI.nama, jumlah_item, catatan ' +
                        'FROM (permohonan_sumber_daya_faskes ps JOIN pengguna p ON ps.username_petugas_faskes = p.username) PE, ' +
                        '(daftar_item d join item_sumber_daya i on d.kode_item_sumber_daya = i.kode) DI, '+
                        'transaksi_sumber_daya T ' +
                        'WHERE PE.no_transaksi_sumber_daya = T.nomor AND DI.no_transaksi_sumber_daya = T.nomor AND T.nomor=' + str(no_transaksi))
        context = {
            "data_permohonan" : cursor.fetchall()
        }
        return render(request, 'detail_permohonan_sumber_daya.html', context)

def update_permohonan_sumber_daya(request, no_transaksi):
    username = request.session['username']
    if request.session['role'] != 'Petugas Faskes':
        return redirect('user:welcome')
    with connection.cursor() as cursor:
        if request.method == "POST":
            no_transaksi = request.POST.get('no_transaksi')

            total_item = request.POST.get('total_item')[0]
            daftar_item = []
            for i in range(int(total_item)):
                daftar_item.append(request.POST.getlist('list_daftar_item[' + str(i) + '][]'))

            cursor.execute(f"DELETE FROM DAFTAR_ITEM WHERE no_transaksi_sumber_daya='{no_transaksi}'")

            insert_item_query = 'INSERT INTO DAFTAR_ITEM values'
            no_urut = 1
            for item in daftar_item:
                insert_item_query += f"({no_transaksi}, {no_urut}, {item[1]}, '{item[0]}'),"
                no_urut+=1
            insert_item_query = insert_item_query[:-1]
            
            catatan = request.POST.get('catatan')

            cursor.execute(insert_item_query)
            cursor.execute(f"DELETE FROM permohonan_sumber_daya_faskes WHERE no_transaksi_sumber_daya='{no_transaksi}'")
            cursor.execute(f"INSERT INTO PERMOHONAN_SUMBER_DAYA_FASKES VALUES('{no_transaksi}','{username}','{catatan}')")

            data = {
                'redirecturl' : "/readPermohonanSumberDaya/"
            }

            return JsonResponse(data)
            
        cursor.execute('SELECT P.nama, D.no_urut, D.kode_item_sumber_daya, D.jumlah_item, PS.catatan ' +
                        'FROM PERMOHONAN_SUMBER_DAYA_FASKES PS, DAFTAR_ITEM D, PENGGUNA P ' +
                        'WHERE PS.no_transaksi_sumber_daya = D.no_transaksi_sumber_daya AND ' +
                        'P.username = PS.username_petugas_faskes AND PS.no_transaksi_sumber_daya=' + str(no_transaksi))
        data_permohonan = list(cursor.fetchall())
        data_permohonan_json = json.dumps(data_permohonan)
        
        cursor.execute('SELECT kode, nama FROM ITEM_SUMBER_DAYA')
        tipe_item = list(cursor.fetchall())

        context = {
            "no_transaksi": no_transaksi,
            "tipe_item": tipe_item,
            "data_permohonan": data_permohonan,
            "data_permohonan_json": data_permohonan_json
        }
        return render(request, 'update_daftar_item.html', context)

def proses_permohonan(request, no_transaksi):
    username = request.session['username']
    if request.session['role'] != 'Admin Satgas':
        return redirect('user:welcome')
    with connection.cursor() as cursor:
        now = date.today().strftime("%Y-%m-%d")
        cursor.execute(f"INSERT INTO RIWAYAT_STATUS_PERMOHONAN values('PRO',{no_transaksi},'{username}','{now}')")
        return redirect('alishayb:read_permohonan_sumber_daya')

def tolak_permohonan(request, no_transaksi):
    username = request.session['username']
    if request.session['role'] != 'Admin Satgas':
        return redirect('user:welcome')
    with connection.cursor() as cursor:
        now = date.today().strftime("%Y-%m-%d")
        cursor.execute(f"INSERT INTO RIWAYAT_STATUS_PERMOHONAN values('REJ',{no_transaksi},'{username}','{now}')")
        return redirect('alishayb:read_permohonan_sumber_daya')

def selesai_permohonan_dengan_masalah(request, no_transaksi):
    username = request.session['username']
    if request.session['role'] != 'Admin Satgas':
        return redirect('user:welcome')
    with connection.cursor() as cursor:
        now = date.today().strftime("%Y-%m-%d")
        cursor.execute(f"INSERT INTO RIWAYAT_STATUS_PERMOHONAN values('MAS',{no_transaksi},'{username}','{now}')")
        return redirect('alishayb:read_permohonan_sumber_daya')

def selesai_permohonan(request, no_transaksi):
    username = request.session['username']
    if request.session['role'] != 'Admin Satgas':
        return redirect('user:welcome')
    with connection.cursor() as cursor:
        now = date.today().strftime("%Y-%m-%d")

alishayb/templates/create_item_sumber_daya.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Buat Item Sumber Daya </title>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>

    <!-- Jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <style>
        body {
            margin: 1em;
        }
    </style>
</head>
<body>
    <h3>Buat Item Sumber Daya</h3>
    <form method="post" class="form-control" action="{% url 'alishayb:create_item_sumber_daya' %}">
        {% csrf_token %}
        {{ create_item_form.as_p }}
        <input type="submit" value="Buat">
    </form>
</body>
</html>

alishayb/templates/create_permohonan_sumber_daya.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Buat Permohonan Sumber Daya</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>

    <style>
        body {
            margin: 1em;
        }
        label {
            display: block;
        }
    </style>

</head>
<body>
    {% if messages %}
    {% for message in messages %}
        <div style="background-color: red; padding: 0.5em; color:white; width:fit-content">
            {{ message }}
        </div>
    {% endfor %}
    {% endif %}

    <h3 class='mb-4 ps-1'> Buat Permohonan Sumber Daya </h3>

    <form method="post" class="form-control" action="{% url 'alishayb:create_transaksi_sumber_daya' %}">
        {% csrf_token %}
        {{permohonan_sumber_daya.as_p}}
        <input type="submit" value="Buat">
    </form>

    
</body>
</html>

alishayb/templates/detail_create_item_sumber_daya.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detail Item Sumber Daya Baru</title>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>

    <!-- Jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <style>
        body {
            margin: 1em;
        }
        label, select {
            display: block;
        }
    </style>
</head>
<body>
    {% if message %}
        <div class="alert alert-success"  role="alert">
            {{ message }}
        </div>
    {% endif %}
    <h3>Detail Item Sumber Daya</h3>
    <form method="post" class="form-control">
        <label for="kode_item" class="ms-2">Kode Item: </label>
        <input type="text" class="mb-4" value="{{kode_item}}" disabled readonly>

        <label for="supplier" class="ms-2">Supplier: </label>
        <input type="text" class="mb-4" value="{{supplier}}" disabled readonly>
        
        <label for="nama_item" class="ms-2">Nama Item: </label>
        <input type="text" class="mb-4" value="{{nama_item}}" disabled readonly>

        <label for="harga_satuan" class="ms-2">Harga Satuan: </label>
        <input type="number" class="mb-4" value="{{harga_satuan}}" disabled readonly>

        <label for="berat_satuan" class="ms-2">Berat Satuan: </label>
        <input type="number" class="mb-4" value="{{berat_satuan}}" disabled readonly>

        <label for="kode_tipe_item" class="ms-2">Kode Tipe Item: </label>
        <input type="text" class="mb-4" value="{{kode_tipe_item}}" disabled readonly>

        <label for="item">Tipe Item:</label>
        <select id="item" class="mb-4" name="item" disabled readonly>
            <option value="{{ kode_tipe_item }}">{{ tipe_item }}</option>
        </select>

        <button type="button" class="mx-auto btn btn-primary" onclick=listItemURL()> Kembali ke List Item </button>
    </form>
    
    <script>
        function listItemURL(){
            location.href = "{% url 'alishayb:read_item_sumber_daya' %}"
        }
    </script>
        
</body>
</html>

alishayb/templates/read_item_sumber_daya.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Item Sumber Daya</title>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>

    <!-- Jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <style>
        body {
            margin: 1em;
        }
    </style>
</head>
<body>
    {% if message %}
        <div class="alert alert-danger"  role="alert">
            {{ message }}
        </div>
    {% endif %}

    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-success"  role="alert">
            {{ message }}
        </div>
    {% endfor %}
    {% endif %}
    
    <h3 class='mb-4 ps-1'> List Item Sumber Daya </h3>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th scope="col">Kode</th>
            <th scope="col">Supplier</th>
            <th scope="col">Nama Item</th>
            <th scope="col">Harga Satuan</th>
            <th scope="col">Berat Satuan (Kg) </th>
            <th scope="col">Tipe Item</th>
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>
            {% for item in list_item %}
                <tr>
                {% for data in item %}
                    {% if data != item.6 %}
                        <td> {{data}} </td>
                    {% endif %}
                {% endfor %}
                
                {% if item.6 == supplier %}
                    <td>
                        <p><a href="{% url 'alishayb:update_item_sumber_daya' item.0 %}"> Update </a></p>
                        <p><a href="{% url 'alishayb:delete_item_sumber_daya' item.0 %}"> Delete </a></p>
                    </td>
                {% endif %}
                
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{% url 'user:dashboard' %}" type="button" class="mx-auto btn btn-primary">Kembali ke Dashboard</a>
</body>
</html>

alishayb/templates/read_permohonan_sumber_daya.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Permohonan Sumber Daya</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>

    <!-- Jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <style>
        body {
            margin: 1em;
        }
        button {
            width: fit-content;
        }
    </style>
</head>

<body class="d-flex flex-column">
    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-success"  role="alert">
            {{ message }}
        </div>
    {% endfor %}
    {% endif %}
    

    <h3 class='mb-4 ps-1'> List Permohonan Sumber Daya </h3>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th scope="col">Nomor</th>
            <th scope="col">Faskes</th>
            <th scope="col">Tanggal Dibuat</th>
            <th scope="col">Total Berat(Kg)</th>
            <th scope="col">Total Item</th>
            <th scope="col" style="width: 30%">Catatan</th>
            <th scope="col">Status</th>
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>
        {% for permohonan in data_permohonan %}
            <tr>
            {% for data in permohonan %}
                {% if data == permohonan.0 %}
                    <td> TREQ{{ data }}</td>
                {% else %}
                    <td> {{ data }} </td>
                {% endif %}
            {% endfor %}
            <td>
                {% if permohonan.6 == "REQ" %}
                    {% if role == "Petugas Faskes" %}
                    <p><a href="{% url 'alishayb:update_permohonan_sumber_daya' permohonan.0 %}">Update</a></p>
                    <p><a href="{% url 'alishayb:delete_permohonan_sumber_daya' permohonan.0 %}">Delete</a></p>
                    {% endif %}
                    {% if role == "Admin Satgas" %}
                    <p><a href="{% url 'alishayb:reject_permohonan' permohonan.0 %}">Reject</a></p>
                    <p><a href="{% url 'alishayb:proses_permohonan' permohonan.0 %}">Process</a></p>
                    {% endif %}
                {% endif %}
                {% if permohonan.6 == "PRO" and role == "Admin Satgas" %}
                <p><a href="{% url 'alishayb:selesai_permohonan_dengan_masalah' permohonan.0 %}">Selesai Dengan Masalah</a></p>
                <p><a href="{% url 'alishayb:selesai_permohonan' permohonan.0 %}">Selesai</a></p>
                {% endif %}
                <p><a href="{% url 'alishayb:detail_permohonan_sumber_daya' permohonan.0 %}">Detail</a></p>
                <p><a href="{% url 'alishayb:riwayat_status_permohonan' permohonan.0 %}">Riwayat Status</a></p>
            </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <button type="button" class="mx-auto btn btn-primary" onclick=createPermohonanURL()>Buat Permohonan Baru</button>
    <a href="{% url 'user:dashboard' %}" type="button" class="mx-auto mt-3 btn btn-primary">Kembali ke Dashboard</a>

    <script>
        function createPermohonanURL(){
            location.href = "{% url 'alishayb:create_transaksi_sumber_daya' %}"
        }
    </script>
</body>
</html>