TK4_E11/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('',include('gilangcy.urls')),
    path('',include('kevin.urls')),
    path('', include('alishayb.urls', namespace="alishayb")),
    path('', include('dodo.urls', namespace="dodo"))
]

dodo/urls.py
from django.urls import path
from . import views

app_name = "dodo"

urlpatterns = [
    path('get-lokasi-alamat/<slug:id_lokasi>', views.locationIDToAddressEndpoint, name="locationIDToAddressEndpoint"),
    path('get-faskes-tipe/<slug:id_tipe>', views.faskesCodeToTypeNameEndpoint, name="faskesCodeToTypeNameEndpoint"),
    path('list-faskes/', views.readFaskes, name="readFaskes"),
    path('delete-faskes/<slug:kode_faskes>', views.deleteFaskes, name="deleteFaskes"),
    path('update-faskes/<slug:kode_faskes>', views.updateFaskes, name="updateFaskes"),
    path('create-faskes/', views.createFaskes, name="createFaskes")
]

gilangcy/urls.py
from django.urls import path
from . import views

app_name = 'gilangcy'

urlpatterns = [
    path('createPesananSumberDaya/', views.createPesananSumberDaya, name='createPesananSumberDaya'),
    path('readPesananSumberDaya/',views.readPesananSumberDaya, name='readPesananSumberDaya'),
    path('deletePesananSumberDaya/<int:delete_id>/',views.deletePesananSumberDaya, name='deletePesananSumberDaya'),
    path('detailPesananSumberDaya/<int:detail_id>/',views.detailPesananSumberDaya, name='detailPesananSumberDaya'),
    path('riwayatStatusPesananSumberDaya/<int:pesanan_id>/',views.riwayatStatusPesananSumberDaya, name='riwayatStatusPesananSumberDaya'),
    path('updatePesananSumberDaya/<int:pesanan_id>/',views.updatePesananSumberDaya, name='updatePesananSumberDaya'),
    path('createRiwayatStatusPesanan/<int:pesanan_id>/<str:kode>',views.createRiwayatStatusPesanan, name='createRiwayatStatusPesanan'),
    path('readStokFaskes/',views.readStokFaskes, name='readStokFaskes'),
    path('createStokFaskes/',views.createStokFaskes, name='createStokFaskes'),
    path('deleteStokFaskes/<str:kode_faskes>/<str:item>',views.deleteStokFaskes, name='deleteStokFaskes'),
    path('updateStokFaskes/<str:kode_faskes>/<str:item>',views.updateStokFaskes, name='updateStokFaskes')
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register',views.register,name='register'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('daftarAdminSatgas/', views.daftar_admin_satgas, name='daftar_admin_satgas'),
    path('daftarPetugasFaskes/', views.daftar_petugas_faskes, name='daftar_petugas_faskes'),
    path('daftarSupplier/', views.daftar_supplier, name='daftar_supplier'),
    path('daftarPetugasDistribusi/', views.daftar_petugas_distribusi, name='daftar_petugas_distribusi')

]

gilangcy/models.py
from django.db import models

# Create your models here.

gilangcy/views.py
from django.shortcuts import redirect, render
from django.db import connection
from django.http import request
from django.contrib import messages

# Create your views here.
def dictfetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def createPesananSumberDaya(request):
    if(request.session['role']!='Admin Satgas'):
        return redirect('user:dashboard')
    with connection.cursor() as cursor:
        if request.method == "POST":
            button = request.POST.get('button')
            new_no_transaksi = request.POST.get('new_no_transaksi')[3:]
            username_supplier = request.POST.get('data_supplier')
            admin_satgas = request.POST.get('admin_satgas')

            if(button == 'simpan'):
                
                insert_into_pesanan_sumber_daya = 'INSERT INTO PESANAN_SUMBER_DAYA VALUES(%s,%s,NULL)'
                tuple_query = [new_no_transaksi,admin_satgas]
                cursor.execute(insert_into_pesanan_sumber_daya,tuple_query)  

                count_total_harga ='SELECT SUM(harga_kumulatif) FROM DAFTAR_ITEM WHERE no_transaksi_sumber_daya = %s'
                tuple_query = [new_no_transaksi]
                cursor.execute(count_total_harga,tuple_query)
                total_harga = cursor.fetchall()[0][0]

                update_total_harga ='UPDATE PESANAN_SUMBER_DAYA SET total_harga = %s WHERE nomor_pesanan = %s'
                tuple_query = [total_harga,new_no_transaksi]
                cursor.execute(update_total_harga,tuple_query)

                return redirect('gilangcy:readPesananSumberDaya')

            elif(button == 'tambah'):

                select_list_item = 'SELECT kode FROM ITEM_SUMBER_DAYA where username_supplier=%s'
                tuple_query = [username_supplier] 
                cursor.execute(select_list_item,tuple_query)  
                list_item = cursor.fetchall()

                list_item_clean =[]
                for data in list_item:
                    list_item_clean.append(data[0])

                step = request.POST.get('step')

                if(step == "1"): 

                    context = {'supplier':username_supplier, 'new_no_transaksi':new_no_transaksi, 'list_item_supplier':list_item_clean,'step':2, 'admin':admin_satgas}

                elif (step == "2") :
                   
                    jumlah_item = request.POST.get('jumlah_item')
                    item = request.POST.get('data_item')

                    select_nomor_item = 'SELECT count(*) FROM daftar_item d, item_sumber_daya i WHERE d.kode_item_sumber_daya=i.kode AND d.no_transaksi_sumber_daya =%s;'
                    tuple_query = [new_no_transaksi]
                    cursor.execute(select_nomor_item,tuple_query)
                    nomor_item = cursor.fetchall()[0][0]

                    try :
                        insert_into_daftar_item = 'INSERT INTO DAFTAR_ITEM VALUES (%s,%s,%s,%s,NULL,NULL)'
                        tuple_query = [new_no_transaksi,nomor_item,jumlah_item,item]
                        cursor.execute(insert_into_daftar_item,tuple_query)

                    except :
                        pass

                    select_daftar_item_dipesan = 'SELECT d.no_urut,i.nama,i.harga_satuan,d.jumlah_item FROM daftar_item d, item_sumber_daya i WHERE d.kode_item_sumber_daya=i.kode AND d.no_transaksi_sumber_daya =%s ORDER BY(d.no_urut)'
                    tuple_query = [new_no_transaksi]
                    cursor.execute(select_daftar_item_dipesan,tuple_query)
                    daftar_item_dipesan = cursor.fetchall()

                    context = {'supplier':username_supplier, 'new_no_transaksi':new_no_transaksi, 'list_item_supplier':list_item_clean,'step':2, 'daftar_item_dipesan':daftar_item_dipesan, 'admin':admin_satgas}

            else :

                select_list_item = 'SELECT kode FROM ITEM_SUMBER_DAYA where username_supplier=%s'
                tuple_query = [username_supplier] 
                cursor.execute(select_list_item,tuple_query)  
                list_item = cursor.fetchall()

                list_item_clean =[]
                for data in list_item:
                    list_item_clean.append(data[0])

                jumlah_item = request.POST.get('jumlah_item')
                item = request.POST.get('data_item')

                delete_item = 'DELETE FROM DAFTAR_ITEM WHERE no_transaksi_sumber_daya=%s AND no_urut=%s;'
                tuple_query = [new_no_transaksi,button]
                cursor.execute(delete_item,tuple_query)

                
                select_daftar_item_dipesan = 'SELECT d.no_urut,i.nama,i.harga_satuan,d.jumlah_item FROM daftar_item d, item_sumber_daya i WHERE d.kode_item_sumber_daya=i.kode AND d.no_transaksi_sumber_daya =%s ORDER BY(d.no_urut)'
                tuple_query = [new_no_transaksi]
                cursor.execute(select_daftar_item_dipesan,tuple_query)
                daftar_item_dipesan = cursor.fetchall()
                
                context = {'supplier':username_supplier, 'new_no_transaksi':new_no_transaksi, 'list_item_supplier':list_item_clean,'step':2, 'daftar_item_dipesan':daftar_item_dipesan, 'admin':admin_satgas}
   
        else :
            admin_satgas = request.session['username']
            cursor.execute('DELETE FROM TRANSAKSI_SUMBER_DAYA WHERE total_berat IS NULL AND total_item IS NULL') 
            step = 1
            cursor.execute('INSERT INTO TRANSAKSI_SUMBER_DAYA(tanggal,total_berat,total_item) VALUES ((SELECT NOW()),NULL,NULL)')  
            fetch = "SELECT nomor FROM TRANSAKSI_SUMBER_DAYA WHERE total_berat IS NULL AND total_item IS NULL"
            cursor.execute(fetch)
            new_no_transaksi = cursor.fetchall()
            new_no_transaksi = new_no_transaksi[0][0]
        
            fetch = "SELECT DISTINCT s.username FROM ITEM_SUMBER_DAYA I, SUPPLIER S WHERE s.username=i.username_supplier ORDER BY s.username ASC"
            cursor.execute(fetch)
            list_data = cursor.fetchall()
            data_supplier =[]
            for data in list_data:
                data_supplier.append(data[0])
            row = dictfetchall(cursor)
            context = {'data_supplier':data_supplier, 'new_no_transaksi':new_no_transaksi, 'step':1, 'admin':admin_satgas}
        return render(request,'createPesananSumberDaya.html',context)

def updatePesananSumberDaya(request,pesanan_id):
    if(request.session['role']!='Admin Satgas'):
        return redirect('user:dashboard')
    with connection.cursor() as cursor:
        if request.method == "POST" :
            button = request.POST.get('button')
            no_transaksi = pesanan_id
            username_supplier = request.POST.get('data_supplier')
            admin_satgas = request.POST.get('admin_satgas')

            if(button == 'simpan'):
                
                delete_pesanan_sumber_daya = "DELETE FROM PESANAN_SUMBER_DAYA WHERE nomor_pesanan =%s "
                tuple_query = [pesanan_id]
                cursor.execute(delete_pesanan_sumber_daya, tuple_query)

                insert_into_pesanan_sumber_daya = 'INSERT INTO PESANAN_SUMBER_DAYA VALUES(%s,%s,NULL)'
                tuple_query = [no_transaksi,admin_satgas]
                cursor.execute(insert_into_pesanan_sumber_daya,tuple_query)  

                count_total_harga ='SELECT SUM(harga_kumulatif) FROM DAFTAR_ITEM WHERE no_transaksi_sumber_daya = %s'
                tuple_query = [no_transaksi]
                cursor.execute(count_total_harga,tuple_query)
                total_harga = cursor.fetchall()[0][0]

                update_total_harga ='UPDATE PESANAN_SUMBER_DAYA SET total_harga = %s WHERE nomor_pesanan = %s'
                tuple_query = [total_harga,no_transaksi]
                cursor.execute(update_total_harga,tuple_query)

                return redirect('gilangcy:readPesananSumberDaya')

            elif(button == 'tambah'):

                select_list_item = 'SELECT kode FROM ITEM_SUMBER_DAYA where username_supplier=%s'
                tuple_query = [username_supplier] 
                cursor.execute(select_list_item,tuple_query)  
                list_item = cursor.fetchall()

                list_item_clean =[]
                for data in list_item:
                    list_item_clean.append(data[0])
                   
                jumlah_item = request.POST.get('jumlah_item')
                item = request.POST.get('data_item')

                select_nomor_item = 'SELECT count(*) FROM daftar_item d, item_sumber_daya i WHERE d.kode_item_sumber_daya=i.kode AND d.no_transaksi_sumber_daya =%s;'
                tuple_query = [no_transaksi]
                cursor.execute(select_nomor_item,tuple_query)
                nomor_item = cursor.fetchall()[0][0]

                try :
                    insert_into_daftar_item = 'INSERT INTO DAFTAR_ITEM VALUES (%s,%s,%s,%s,NULL,NULL)'
                    tuple_query = [no_transaksi,nomor_item,jumlah_item,item]
                    cursor.execute(insert_into_daftar_item,tuple_query)
                except :
                    pass

                select_daftar_item_dipesan = 'SELECT d.no_urut,i.nama,i.harga_satuan,d.jumlah_item FROM daftar_item d, item_sumber_daya i WHERE d.kode_item_sumber_daya=i.kode AND d.no_transaksi_sumber_daya =%s ORDER BY(d.no_urut)'
                tuple_query = [no_transaksi]
                cursor.execute(select_daftar_item_dipesan,tuple_query)
                daftar_item_dipesan = cursor.fetchall()

                context = {'supplier':username_supplier, 'no_transaksi':no_transaksi, 'list_item_supplier':list_item_clean, 'daftar_item_dipesan':daftar_item_dipesan, 'admin':admin_satgas}

            else :

                select_list_item = 'SELECT kode FROM ITEM_SUMBER_DAYA where username_supplier=%s'
                tuple_query = [username_supplier] 
                cursor.execute(select_list_item,tuple_query)  

gilangcy/templates/createPesananSumberDaya.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</head>
<body>
    <a href="{% url 'user:dashboard' %}">Dashboard</a>
    <h1 style="text-align: center;">Create Pesanan Sumber Daya</h1>
    {% if step == 1 %}
    <form method="POST" action="{% url 'gilangcy:createPesananSumberDaya' %}">
        <input type="text" hidden value="{{step}}" name="step">
        {% csrf_token %}
        <p>No Transaksi :</p> 
        {% if new_no_transaksi < 10 %}
        <input class="form-control" type="text" readonly id="new_no_transaksi" name="new_no_transaksi" value="TOR0{{new_no_transaksi}}">
        {% else %}
        <input class="form-control" type="text" readonly id="new_no_transaksi" name="new_no_transaksi" value="TOR{{new_no_transaksi}}">
        {% endif %}
        <br/>
        <p>Petugas :</p>
        <input class="form-control" type="text" readonly id="admin_satgas" name="admin_satgas" value="{{admin}}"> 
        <p>Supplier</p> 
        <select class="form-control" id="data_supplier" name="data_supplier">
            {% for supplier in data_supplier %}
            <option value="{{ supplier }}">{{ supplier }}</option>
            {% endfor %}
          </select>
    <button name="button" type="submit" value="tambah">Pilih Supplier</button>
    </form>
    {% endif %}

    {% if step == 2 %}
    <form method="post" action="{% url 'gilangcy:createPesananSumberDaya' %}"> 
        <input type="text" hidden value="{{step}}" name="step">
        {% csrf_token %}
        <p>No Transaksi :</p> 
        {% if new_no_transaksi < 10 %}
        <input class="form-control" type="text" readonly id="new_no_transaksi" name="new_no_transaksi" value="TOR0{{new_no_transaksi}}">
        {% else %}
        <input class="form-control" type="text" readonly id="new_no_transaksi" name="new_no_transaksi" value="TOR{{new_no_transaksi}}">
        {% endif %}
        <br/>
        <p>Petugas :</p>
        <input class="form-control" type="text" readonly id="admin_satgas" name="admin_satgas" value="{{admin}}"> 
        <p>Supplier</p> 
        <input class="form-control" type="text" readonly id="data_supplier" name="data_supplier" value="{{supplier}}">
        <br/>
        <p style=>Daftar Item</p>
        <table class="table">
            <tr>
                <td>
                    No Urut
                </td>
                <td>
                    Nama
                </td>
                <td>
                    Harga Satuan
                </td>
                <td>
                    Jumlah Item
                </td>
                <td>
                    Action
                </td>
            </tr>
            {% for item in daftar_item_dipesan %}
            <tr>
                <td>{{ item.0 }}</td>   
                <td>{{ item.1 }}</td>   
                <td>{{ item.2 }}</td>   
                <td>{{ item.3 }}</td>   
                <td><button name="button" value="{{item.0}}" type="submit" class="btn btn-danger">Delete</button> </td> 
            </tr>
            {% endfor %}
        </table>
        <p>Tambah Item</p> 
        <select class="form-control" id="data_item" name="data_item">
            {% for item in list_item_supplier %}
            <option value="{{ item }}">{{ item }}</option>
            {% endfor %}
          </select>
        <br/>
        <p>Jumlah :</p>
        <input class= "form-control" type="number" name="jumlah_item" id="jumlah_item" >
        <br/>
        <div  class="form-control" id="list-item" name="list-item">
        </div>
    <button name="button" value="tambah" type="submit">Tambah Item</button>
    <button name="button" value="simpan" type="submit">Simpan Transaksi</button>
    </form>
    {% endif %}

</html>

gilangcy/templates/createStokFaskes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</head>
<body>
    <a href="{% url 'user:dashboard' %}">Dashboard</a>
    <h1 style="text-align: center;">Create Stok Faskes</h1>
    {% if step == 1 %}
    <form method="POST" action="{% url 'gilangcy:createStokFaskes' %}">
        <input type="text" hidden value="{{step}}" name="step">
        {% csrf_token %}
        <p>Kode Faskes</p> 
        <select class="form-control" id="kode_faskes" name="kode_faskes">
            {% for faskes in list_faskes %}
            <option value="{{ faskes.0 }}">{{ faskes.0 }}</option>
            {% endfor %}
          </select>
    <button name="button" type="submit" value="submit">Pilih Faskes</button>
    </form>
    {% endif %}

    {% if step == 2 %}
    <form method="POST" action="{% url 'gilangcy:createStokFaskes' %}">
        <input type="text" hidden value="{{step}}" name="step">
        {% csrf_token %}
        <p>Kode Faskes</p> 
        <input class="form-control" type="text" readonly id="kode_faskes" name="kode_faskes" value="{{kode_faskes}}">
        <p>Faskes</p> 
        <input class="form-control" type="text" readonly id="faskes" name="faskes" value="{{faskes}}">
        <p>Item</p>
        <select class="form-control" id="list_item" name="list_item">
            {% for item in list_item %}
            <option value="{{ item.0 }}">{{ item.0 }}</option>
            {% endfor %}
          </select>
    <button name="button" type="submit" value="submit">Pilih Item</button>
    </form>
    </form>
    {% endif %}

    {% if step == 3 %}
    <form method="POST" action="{% url 'gilangcy:createStokFaskes' %}">
        <input type="text" hidden value="{{step}}" name="step">
        {% csrf_token %}
        <p>Kode Faskes</p> 
        <input class="form-control" type="text" readonly id="kode_faskes" name="kode_faskes" value="{{kode_faskes}}">
        <p>Faskes</p> 
        <input class="form-control" type="text" readonly id="faskes" name="faskes" value="{{faskes}}">
        <p>Kode Item</p>
        <input class="form-control" type="text" readonly id="kode_item" name="kode_item" value="{{kode_item}}">
        <p>Nama Item</p>
        <input class="form-control" type="text" readonly id="item" name="item" value="{{item}}">
        <p>Jumlah</p>
        <input class= "form-control" type="number" name="jumlah_item" id="jumlah_item" required>
    <button name="button" type="submit" value="submit">Simpan</button>
    </form>
    {% endif %}

</html>

gilangcy/templates/readPesananSumberDaya.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
    <a href="{% url 'user:dashboard' %}">Dashboard</a>
    <h1 style="text-align: center;">Pesanan Sumber Daya</h1>
    <table class="table table-border">
        <tr>
            <td>
                No Pesanan
            </td>
            <td>
                Username admin
            </td>
            <td>
                Tanggal
            </td>
            <td>
                Berat Total
            </td>
            <td>
                Jumlah Item
            </td>
            <td>
                Harga Total
            </td>
            <td>
                Status Pesanan
            </td>
            <td>
                Action
            </td>
        </tr>
        {% for elem in daftar %}
        <tr>
            {% if elem.0 < 10 %}
            <td>TOR0{{ elem.0 }}</td>   
            {% else %}
            <td>TOR{{ elem.0 }}</td> 
            {% endif %}
            <td>{{ elem.1 }}</td>   
            <td>{{ elem.2 }}</td>   
            <td>{{ elem.3 }}</td>  
            <td>{{ elem.4 }}</td>  
            <td>Rp.{{ elem.5 }}</td>  
            <td>{{ elem.6 }}</td>   
            <td>
                {% if role == 'Admin Satgas' %}
                    {% if elem.6 == "REQ-SUP" %}
                    <a href="{% url 'gilangcy:updatePesananSumberDaya' pesanan_id=elem.0 %}" name ="update"value="update" type="submit" class="btn border-dark">Update</a></br></br>
                    <a href="{% url 'gilangcy:deletePesananSumberDaya' delete_id=elem.0 %}" name="button" value="delete" type="submit" class="btn border-dark">Delete</a></br></br>
                    {% endif %}
                {% else %}
                    {% if elem.6 == "REQ-SUP" %}
                    <a href="{% url 'gilangcy:createRiwayatStatusPesanan' pesanan_id=elem.0 kode='REJ-SUP' %} " name="button" value="reject" type="submit" class="btn border-dark">Reject</a></br></br>
                    <a href="{% url 'gilangcy:createRiwayatStatusPesanan' pesanan_id=elem.0 kode='PRO-SUP' %}" name="button" value="process" type="submit" class="btn border-dark">Process</a></br></br>
                    {% elif elem.6 == "PRO-SUP" %}
                    <a href="{% url 'gilangcy:createRiwayatStatusPesanan' pesanan_id=elem.0 kode='MAS-SUP' %}" name="button" value="selesai-dengan-masalah" type="submit" class="btn border-dark">Selesai dengan Masalah</a></br></br>
                    <a href="{% url 'gilangcy:createRiwayatStatusPesanan' pesanan_id=elem.0 kode='FIN-SUP' %}" name="button" value="selesai" type="submit" class="btn border-dark">Selesai</a></br></br>
                    {% endif %}
                {% endif %}
                <a href="{% url 'gilangcy:detailPesananSumberDaya' detail_id=elem.0 %}" name="button" value="detail" type="submit" class="btn border-dark">Detail</a></br></br>
                <a href="{% url 'gilangcy:riwayatStatusPesananSumberDaya' pesanan_id=elem.0 %}" name="button" value="riwayat" type="submit" class="btn border-dark">Riwayat Status</a></br></br>
             </td> 
        </tr>
        {% endfor %}
    </table>
    {% if role == 'Admin Satgas' %}
    <center>
    <a href="{% url 'gilangcy:createPesananSumberDaya' %}" name="button" value="riwayat_status" type="submit" class="btn border-dark"">Tambah</a></br></br>
    </center>
    {% endif %}
</body>
</html>

gilangcy/templates/readStokFaskes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
    <a href="{% url 'user:dashboard' %}">Dashboard</a>
    <h1 style="text-align: center;">Stok Faskes</h1>
    <table class="table table-border">
        <tr>
            <td>
                Kode Faskes
            </td>
            <td>
                Nama Faskes
            </td>
            <td>
                Item Sumber Daya
            </td>
            <td>
                Jumlah
            </td>
            {% if role == 'Admin Satgas' %}
            <td>
                Action
            </td>
            {% endif %}
        </tr>
        {% for elem in list_stok_faskes %}
        <tr>
            <td>{{ elem.0 }}</td>
            <td>{{ elem.1 }}</td>   
            <td>{{ elem.2 }}</td>   
            <td>{{ elem.3 }}</td>  
            {% if role == 'Admin Satgas' %}
            <td>
                <a href="{% url 'gilangcy:updateStokFaskes' kode_faskes=elem.0 item=elem.2  %}" name ="update"value="update" type="submit" class="btn border-dark">Update</a></br></br>
                <a href="{% url 'gilangcy:deleteStokFaskes' kode_faskes=elem.0 item=elem.2  %}" name="button" value="delete" type="submit" class="btn border-dark">Delete</a></br></br>
             </td> 
            {% endif %}
        </tr>
        {% endfor %}
    </table>
    {% if role == 'Admin Satgas' %}
    <center>
    <a href="{% url 'gilangcy:createStokFaskes' %}" name="button" value="riwayat_status" type="submit" class="btn border-dark"">Tambah</a></br></br>
    </center>
    {% endif %}
</body>
</html>